### ISSUE TITLE
Backpressure exceptions emitted to subscribers with backpressure strategy

### ISSUE THREAD

**Issue by justintuchek** [JakeWharton/RxRelay#19]
Do Relays respect backpressure? or are they similar to Subjects in that manner? (reading https://www.reddit.com/r/androiddev/comments/4ba3an/rxjava_the_problem_with_subjects/)

I'm using a PublishRelay that updates every 100ms w/ 4 subscribers, all of which apply `onBackPressureLatest()` - but I seem to be getting `rx.exceptions.MissingBackpressureException` regardless.

Is this the wrong way to approach the problem, or maybe a mistake on my part?

For example:
``` java
// Single Source
PublishRelay<State> state = PublishRelay.create();
        // Multiple subscribers as below
        Subscription stateSubscription = state
                .observeOn(AndroidSchedulers.mainThread())
                .onBackpressureLatest()
                .subscribe(new Observer<State>() {
                    @Override
                    public void onCompleted() {
                        // do foo
                    }

                    @Override
                    public void onError(Throwable e) {
		       // do baz
                    }

                    @Override
                    public void onNext(State state) {
			// do 42
                    }
                });
```

Resulting stacktrace:
```java
11-11 09:27:47.064 2708-2708/? E/UncaughtException: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                        at android.os.Looper.loop(Looper.java:154)
                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                     Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187)
                                                        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                        at rx.internal.operators.OperatorOnBackpressureLatest$LatestEmitter.emit(OperatorOnBackpressureLatest.java:173)
                                                        at rx.internal.operators.OperatorOnBackpressureLatest$LatestEmitter.onError(OperatorOnBackpressureLatest.java:137)
                                                        at rx.internal.operators.OperatorOnBackpressureLatest$LatestSubscriber.onError(OperatorOnBackpressureLatest.java:216)
                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273)
                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                        at android.os.Looper.loop(Looper.java:154) 
                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                     Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187) 
                                                        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) 
                                                        at rx.internal.operators.OperatorOnBackpressureLatest$LatestEmitter.emit(OperatorOnBackpressureLatest.java:173) 
                                                        at rx.internal.operators.OperatorOnBackpressureLatest$LatestEmitter.onError(OperatorOnBackpressureLatest.java:137) 
                                                        at rx.internal.operators.OperatorOnBackpressureLatest$LatestSubscriber.onError(OperatorOnBackpressureLatest.java:216) 
                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273) 
                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216) 
                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107) 
                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                        at android.os.Looper.loop(Looper.java:154) 
                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                     Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                        at com.*B*.app.*B*Application$1.handleError(*B*Application.java:55)
                                                        at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:116)
                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                        at android.os.Looper.loop(Looper.java:154) 
                                                        at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                     Caused by: rx.exceptions.MissingBackpressureException
                                                        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:160)
                                                        at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:205)
                                                        at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
                                                        at com.*B*.app.ui.control.MissionControlPresenter$1.onNext(MissionControlPresenter.java:147)
                                                        at com.*B*.app.ui.control.MissionControlPresenter$1.onNext(MissionControlPresenter.java:134)
                                                        at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                                                        at rx.internal.operators.OperatorOnBackpressureLatest$LatestEmitter.emit(OperatorOnBackpressureLatest.java:165)
                                                        at rx.internal.operators.OperatorOnBackpressureLatest$LatestEmitter.onNext(OperatorOnBackpressureLatest.java:131)
                                                        at rx.internal.operators.OperatorOnBackpressureLatest$LatestSubscriber.onNext(OperatorOnBackpressureLatest.java:211)
                                                        at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
                                                        at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
                                                        at rx.Scheduler$Worker$1.call(Scheduler.java:137)
                                                        at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
                                                        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                        at java.lang.Thread.run(Thread.java:761)
                                                     Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
                                                        at com.*B*.app.*B*Application$1.handleError(*B*Application.java:55)
11-11 09:27:47.064 2708-2708/? E/UncaughtException:     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:116)
                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                        at android.os.Looper.loop(Looper.java:154)
                                                        at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by kkovach** [comment]
I believe I was having the same experience so I did some Googling and found this, http://stackoverflow.com/questions/31815989/how-to-buffer-only-latest-emission-from-rx-observable-during-backpressure where the OP noted "As an added note, I had to call this operator between subscribeOn(Schedulers.io()) and observeOn(AndroidSchedulers.mainThread()) to get it to work."

It helped me. Maybe it will help you?
