### ISSUE TITLE
PublishRelay as flowable throws MissingBackpressureException.

### ISSUE THREAD

**Issue by tejasna** [JakeWharton/RxRelay#28]
I'm using the following versions : 

rxrelay2:rxrelay:2.0.0 
rxjava2:rxjava:2.0.1'

I'm using a simple PublishRelay object to notify multiple subscribers about different events in my app, which looks like this:

``` 
public abstract class RxBus {
  private final Relay<Object> _bus = PublishRelay.create().toSerialized();

  public void send(Object o) {
    _bus.accept(o);
  }

  public Flowable<Object> asFlowable() {
    return _bus.toFlowable(BackpressureStrategy.DROP);
  }

  public boolean hasObservers() {
    return _bus.hasObservers();
  }
}
```
RxRelay Impl :

```
public class RxEventBus extends RxBus {

  private static RxBus rxBus = null;

  private RxPusherEventBus() {
  }

  public static RxBus getRxBusSingleton() {
    if (rxBus == null) {
      rxBus = new RxEventBus();
    }
    return rxBus;
  }
}
```
Overall Implementation looks like this:

```
_disposables.add(RxEventBus.getRxBusSingleton()
        .asFlowable()
        .onBackpressureDrop()
        .subscribeOn(io.reactivex.schedulers.Schedulers.io())
        .doOnError(throwable -> Timber.e(throwable.getMessage()))
        .onErrorReturnItem(Flowable.empty())
        .observeOn(io.reactivex.android.schedulers.AndroidSchedulers.mainThread())
        .subscribe(o -> {
         << doing some stuff >>
         }, this::errorHandler));
```
The error handler : 

```
  private void errorHandler(Throwable throwable) {
    Timber.e(throwable.getMessage());
  }
```
Though i've added a back pressure strategy to the relay and the onBackpressureDrop() operator ( to the subscription (not sure if its an overkill) I get the following stack trace : 

```
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: xyz.lisn, PID: 17283
                                                          java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                                                              at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:154)
                                                              at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                           Caused by: rx.exceptions.OnErrorNotImplementedException
                                                              at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
                                                              at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
                                                              at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                              at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
                                                              at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                              at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
                                                              at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:264)
                                                              at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:207)
                                                              at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                              at android.os.Handler.handleCallback(Handler.java:751) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                              at android.os.Looper.loop(Looper.java:154) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                           Caused by: rx.exceptions.MissingBackpressureException
                                                              at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:150)
                                                              at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
                                                              at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
                                                              at rx.Scheduler$Worker$1.call(Scheduler.java:134)
                                                              at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:186)
                                                              at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                              at java.lang.Thread.run(Thread.java:761)
```
I'm not sure what's going wrong, i've tried re-ordering the onBackPressureDrop() operator to be in between the subscribeOn and observeOn operators, without any luck. 
Thanks in advance.

**Comment by Zhuinden** [comment]
How can you have exception from `rx.` package if you are using RxJava2 which is `io.reactivex`?

**Comment by JakeWharton** [comment]
I'm going to close because RxJava 1.x is at end-of-life and relays should have no different behavior than subjects in this regard. There is no backpressure in RxJava 2.x relays at all.
