### ISSUE TITLE
ReplayRelay NullPointerException

### ISSUE THREAD

**Issue by bentrengrove** [JakeWharton/RxRelay#46]
Apologies if my error, rx stack traces are hard to understand. We are getting an NPE using ReplayRelay. Attached is the stack trace.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.concurrent.atomic.AtomicReference.get()' on a null object reference
       at com.jakewharton.rxrelay2.ReplayRelay$SizeBoundReplayBuffer.replay(ReplayRelay.java:683)
       at com.jakewharton.rxrelay2.ReplayRelay.subscribeActual(ReplayRelay.java:221)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:475)
       at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.onSubscribe(ObservableConcatMap.java:330)
       at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:31)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:55)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.subscribe(ObservableCombineLatest.java:117)
       at io.reactivex.internal.operators.observable.ObservableCombineLatest.subscribeActual(ObservableCombineLatest.java:71)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged.subscribeActual(ObservableDistinctUntilChanged.java:35)
       at io.reactivex.Observable.subscribe(Observable.java:12090)
       at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
       at io.reactivex.Flowable.subscribe(Flowable.java:14479)
       at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)
       at io.reactivex.Flowable.subscribe(Flowable.java:14479)
       at io.reactivex.Flowable.subscribe(Flowable.java:14426)
       at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by JakeWharton** [comment]
Version?

**Comment by bentrengrove** [comment]
2.1.0

**Comment by JakeWharton** [comment]
Any chance you can create a test case or executable sample that reproduces
this?

**Comment by bentrengrove** [comment]
Same bug happens when we switch to ReplaySubject so I think it might be something on our end or RxJava.

**Comment by dawidhyzy** [comment]
@bentrengrove Have the same issue. Is there a chance that you remember what was the problem here?

**Comment by bentrengrove** [comment]
We never worked it out unfortunately, just replaced that code with
something else

**Comment by hujim** [comment]
FYI: For those that still encountered this like us, I think it's it relates to, and is fixed by this
https://github.com/ReactiveX/RxJava/pull/6602

**Comment by JakeWharton** [comment]
I'd take a PR with the equivalent changes to the relays here. I don't have time to do it for a while, unfortunately.
